const quotes = [
  "Quem sabe o que quer, encontra o caminho. — Coelho Neto",
  "Toda conquista começa com a decisão de tentar. — Anônimo",
  "Disciplina é a ponte entre metas e conquistas. — Anônimo",
  "Cada não te aproxima do próximo sim. — Anônimo",
  "Grandes resultados nascem de pequenos hábitos diários. — James Clear, Atomic Habits",
  "Persistência transforma esforço em recompensa. — Anônimo",
  "Quem faz acontece, todo dia. — Anônimo",
  "Sua próxima venda está a uma ligação de distância. — Anônimo",
  "Metas se cumprem por quem não desiste no meio do caminho. — Anônimo",
  "Consistência vale mais que intensidade. — Anônimo",
  "Vá além do combinado. É lá que mora o bônus. — Anônimo",
  "Trabalhe hoje pela vitória de amanhã. — Anônimo",
  "Não conte os dias, faça os dias contarem. — Muhammad Ali",
  "Excelência é hábito, não sorte. — Aristóteles",
  "Confiança se constrói com prática, não com desejo. — Anônimo",
  "Comprometimento é o preço da meta batida. — Anônimo",
  "Tudo posso naquele que me fortalece. — Filipenses 4:13",
  "Os que confiam no Senhor são como os montes de Sião: não se abalam, mas permanecem para sempre. — Salmos 125:1",
  "Se Deus é por nós, quem será contra nós? — Romanos 8:31",
  "O homem habilidoso chegará a governos. — Provérbios 22:29",
  "Seja forte e corajoso; não tema, nem se espante, porque o Senhor teu Deus é contigo. — Josué 1:9",
  "Tudo o que fizerdes, fazei-o de todo o coração. — Colossenses 3:23",
  "A persistência realiza o que a sorte não alcança. — Provérbio popular",
  "Venda é transferência de entusiasmo. — Zig Ziglar",
  "Você pode ter tudo na vida que quiser, se ajudar outras pessoas a terem o que querem. — Zig Ziglar",
  "O segredo do sucesso é a constância do propósito. — Benjamin Disraeli",
  "Faça o que você tem que fazer, até poder fazer o que você quer fazer. — Oprah Winfrey",
  "O talento vence jogos, mas o trabalho em equipe e a inteligência vencem campeonatos. — Michael Jordan",
  "Não tenha medo de desistir do bom para ir atrás do ótimo. — John D. Rockefeller",
  "O fracasso é apenas a oportunidade de recomeçar com mais inteligência. — Henry Ford",
  "O sucesso é a soma de pequenos esforços repetidos dia após dia. — Robert Collier",
  "A melhor maneira de prever o futuro é criá-lo. — Peter Drucker",
  "Não há atalhos para qualquer lugar que valha a pena. — Beverly Sills",
  "A vida é 10% do que acontece e 90% de como reagimos. — Charles R. Swindoll",
  "Seja a mudança que você quer ver no mundo. — Mahatma Gandhi",
  "O sucesso não é o final, o fracasso não é fatal: é a coragem para continuar que conta. — Winston Churchill",
  "A coragem não é ausência de medo; é agir apesar dele. — Mark Twain",
  "Em tudo, dai graças, porque esta é a vontade de Deus em Cristo Jesus para vós. — 1 Tessalonicenses 5:18",
  "Esforça-te, e tem bom ânimo. — Josué 1:9",
  "Tudo tem o seu tempo determinado. — Eclesiastes 3:1",
  "Se a fé te deixou pequeno, levante-se. Ainda há muitas vendas para fazer. — Anônimo",
];

export function quoteOfTheDay(date = new Date()): string {
  const day = Math.floor(date.getTime() / 86_400_000);
  return quotes[day % quotes.length]!;
}
